### ISSUE TITLE
OpenGL error on X11 (fedora 30 , chromium 74.0.3729.108-1)

### ISSUE THREAD

**Issue by ghost** [biswasab/chromium_vaapi_fed#9] opened 2019-05-05 10:12 UTC
`Log Messages
[23961:23961:0505/120628.031128:ERROR:vaapi_wrapper.cc(619)] : vaQueryConfigEntrypoints failed VA error: the requested VAProfile is not supported
[23961:23961:0505/120628.031222:ERROR:vaapi_wrapper.cc(619)] : vaQueryConfigEntrypoints failed VA error: the requested VAProfile is not supported
[23961:23961:0505/120628.089511:ERROR:sandbox_linux.cc(368)] : InitializeSandbox() called with multiple threads in process gpu-process.
[23961:23961:0505/120628.943843:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[23961:23961:0505/120632.540584:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[23961:23961:0505/120638.769984:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[23961:23961:0505/120649.817007:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[23961:23961:0505/120858.511583:ERROR:buffer_manager.cc(488)] : `

chromium creates black rectangles in menus and windows along with artifacts making it impossible to display content

Intel i5vPro 3437U GPU intel HD 4000

**Comment by qnixsynapse** [comment] 2019-05-05 10:37
@ilcaravaggio Can you please try disabling rasterization?

Edit /usr/bin/chromium-vaapi

![Screenshot_20190505_155009](https://user-images.githubusercontent.com/17230826/57192404-a56c1680-6f4d-11e9-9155-aac73ee7003b.png)

^^ delete the line starting with `--enable-gpu-rasterization \`

**Comment by ghost** [comment] 2019-05-05 10:46
> /usr/bin/chromium-vaapi


tried but the problem remains




`[6973:6973:0505/124351.804897:ERROR:vaapi_wrapper.cc(619)] : vaQueryConfigEntrypoints failed VA error: the requested VAProfile is not supported
[6973:6973:0505/124351.805089:ERROR:vaapi_wrapper.cc(619)] : vaQueryConfigEntrypoints failed VA error: the requested VAProfile is not supported
[6973:6973:0505/124351.863371:ERROR:sandbox_linux.cc(368)] : InitializeSandbox() called with multiple threads in process gpu-process.
[6973:6973:0505/124352.761877:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124420.725010:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124536.303475:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124538.076862:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124614.238749:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124616.729075:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124626.527643:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124629.665613:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124630.391307:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124631.048824:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124631.568942:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124632.122478:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124632.720411:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124633.240055:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6973:6973:0505/124644.667992:ERROR:buffer_manager.cc(488)] : `

**Comment by qnixsynapse** [comment] 2019-05-05 12:11
@ilcaravaggio Can you reproduce it in google chrome?

**Comment by ghost** [comment] 2019-05-05 12:54
> @ilcaravaggio Can you reproduce it in google chrome?
it seems a common problem with chrome 74
`Log Messages
[16926:16926:0505/145208.152305:ERROR:sandbox_linux.cc(368)] : InitializeSandbox() called with multiple threads in process gpu-process.
[16926:16926:0505/145208.657256:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[16926:16926:0505/145212.124083:WARNING:x11_util.cc(1422)] : X error received: serial 926, error_code 168 (GLXBadWindow), request_code 151, minor_code 32 (X_GLXDestroyWindow)
[16926:16926:0505/145212.136153:WARNING:x11_util.cc(1422)] : X error received: serial 930, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
[16926:16926:0505/145212.136635:ERROR:buffer_manager.cc(488)] : [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[16926:16926:0505/145233.796711:ERROR:buffer_manager.cc(488)] : `

**Comment by qnixsynapse** [comment] 2019-05-05 13:34
@ilcaravaggio  Which desktop environment/compositor are you running? If it started occuring in 74, I would recommend you to open a bug report upstream. Possible a problem with intel driver itself.

**Comment by ghost** [comment] 2019-05-05 13:56
> Which desktop environment/compositor are you running? If it started occuring in 74, I would recommend you to open a bug report upstream. Possible a problem with intel driver itself.


use gnome 3.32.1 kernel 5.0.11

>    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ivybridge Mobile  (0x166)
    Version: 19.0.3
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0

> server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 4.2 (Core Profile) Mesa 19.0.3
OpenGL core profile shading language version string: 4.20
OpenGL version string: 3.0 Mesa 19.0.3
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

on dmesg I also noticed this:

`[    4.121170] [drm:intel_set_cpu_fifo_underrun_reporting [i915]] *ERROR* uncleared fifo underrun on pipe A
[    4.121196] [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun
[    4.121229] [drm:intel_set_pch_fifo_underrun_reporting [i915]] *ERROR* uncleared pch fifo underrun on pch transcoder A
[    4.121246] [drm:cpt_irq_handler [i915]] *ERROR* PCH transcoder A FIFO underrun
`

**where do you advise me to report bugs?**

**Comment by qnixsynapse** [comment] 2019-05-05 14:07
@ilcaravaggio  Best place for this is https://bugzilla.kernel.org.

**Comment by ghost** [comment] 2019-05-05 14:37
> @ilcaravaggio Best place for this is https://bugzilla.kernel.org.

I reported errors of DRM on freedesktop.org and the chrome log on the project website.
however, the fact remains that it does not depend on intel.
versions 72 and 73 on the same system do not suffer this problem: -S

**Comment by qnixsynapse** [comment] 2019-05-05 14:41
> versions 72 and 73 on the same system do not suffer this problem: -S

@ilcaravaggio Then it should go to https://bugs.chromium.org/p/chromium/issues/list

**Comment by ghost** [comment] 2019-05-05 14:48
> > versions 72 and 73 on the same system do not suffer this problem: -S
> 
> @ilcaravaggio Then it should go to https://bugs.chromium.org/p/chromium/issues/list

https://bugs.chromium.org/p/chromium/issues/detail?id=959635&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by qnixsynapse** [comment] 2019-05-05 15:00
@ilcaravaggio Why have you put the chromium-vaapi's chrome://gpu page? Most chances are that they will close it. You should put the google chrome's chrome://gpu page.

**Comment by ghost** [comment] 2019-05-05 15:15
oh damn! XD

I can't change it


I will insert a second comment with the right log

**Comment by qnixsynapse** [comment] 2019-05-05 15:27
@ilcaravaggio LOL :D If they ask you tell them that this also happens on google chrome. Anyways, closing this bug. Thank you for the report.

**Closed as completed by qnixsynapse** 2019-05-05 15:27 UTC
Labels: Upstream

**Comment by ghost** [comment] 2019-05-05 15:37
> @ilcaravaggio LOL :D If they ask you tell them that this also happens on google chrome. Anyways, closing this bug. Thank you for the report.


thank you for your time! :-D

small question off topic and I close the speech.
Have you tried building chromium ozone wayland? on copr not have h264: -S

**Comment by qnixsynapse** [comment] 2019-05-05 15:59
Yes but it's on copr. And obviously it won't have h264. , Thing is it doesn't matter because as soon as you play the video, it will crash. See: https://bugs.chromium.org/p/chromium/issues/detail?id=929632
